server:
  port: 8200
spring:
  application:
    name: spring-cloud-dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  scan:
    base-packages: com.wyc.dubbo.provider
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（-1 表示自增端口， 从20880开始）
    port: -1
