server:
  port: 8300
spring:
  application:
    name: spring-cloud-dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
dubbo:
  cloud:
    subscribed-services: spring-cloud-dubbo-provider